

import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import type { TransportRequest } from '@/lib/types';
import { format } from 'date-fns';
import { Separator } from '../ui/separator';

interface RequestDetailsDialogProps {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
  request: TransportRequest;
}

const DetailItem = ({ label, value }: { label: string; value?: string | null }) =>
  value ? (
    <div>
      <p className="text-sm font-medium text-muted-foreground">{label}</p>
      <p className="whitespace-pre-wrap">{value}</p>
    </div>
  ) : null;


export default function RequestDetailsDialog({ isOpen, setIsOpen, request }: RequestDetailsDialogProps) {

  const getStage = () => {
    switch (request.status) {
        case 'Pending':
            return 'With PD';
        case 'Recommended':
        case 'Not Recommended':
            return 'With Supervisor';
        case 'Forwarded':
            return 'With Manager';
        case 'Approved':
        case 'Disapproved':
            return 'Completed';
        default:
            return 'Unknown';
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="sm:max-w-2xl printable" data-dialog-content>
        <DialogHeader className="text-center">
          <DialogTitle className="text-xl font-bold">Transport Management System</DialogTitle>
          <DialogDescription>
            Vehicle Requisition Request
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4 max-h-[80vh] overflow-y-auto pr-6">
            
            {request.officials && request.officials.length > 0 && (
              <>
                <h4 className="font-semibold">Officials</h4>
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-sm font-medium text-muted-foreground px-2">
                    <p>Name</p>
                    <p>Employee Number</p>
                  </div>
                  {request.officials.map((official, index) => (
                    <div key={index} className="flex justify-between items-center text-sm p-2 bg-muted/50 rounded-md">
                      <p>{official.name}</p>
                      <p className="text-muted-foreground">{official.employeeNumber}</p>
                    </div>
                  ))}
                </div>
                <Separator />
              </>
            )}

            <h4 className="font-semibold">Request Generated By</h4>
            <div className="grid grid-cols-2 gap-4">
                <DetailItem label="Employee Number" value={request.employeeNumber} />
                <DetailItem label="Employee Name" value={request.name} />
            </div>

            <Separator />
            
            <div className="grid grid-cols-2 gap-4">
                <DetailItem label="From Location" value={request.departingLocation} />
                <DetailItem label="Destination" value={request.destination} />
                <DetailItem label="Start Time" value={format(new Date(request.from), 'PPP p')} />
                <DetailItem label="End Time" value={format(new Date(request.to), 'PPP p')} />
            </div>

            <Separator />

            <div className='space-y-4'>
                <DetailItem label="Reason" value={request.requestReason} />
                 {request.requestReason === 'For Meeting' && (
                    <div className="grid grid-cols-2 gap-4 pl-4 border-l-2">
                        <DetailItem label="Letter ID with Date" value={request.letterId} />
                        <DetailItem label="Venue" value={request.venue} />
                        <div className="col-span-2">
                            <DetailItem label="Meeting Agenda" value={request.meetingAgenda} />
                        </div>
                    </div>
                )}

                {request.requestReason === 'For Purchase' && (
                    <div className="grid grid-cols-2 gap-4 pl-4 border-l-2">
                        <DetailItem label="Purchase Case Number" value={request.purchaseCaseNumber} />
                        <DetailItem label="Subject" value={request.subject} />
                         <div className="col-span-2">
                            <DetailItem label="Details of Purchase" value={request.purchaseDetails} />
                        </div>
                         <div className="col-span-2">
                            <DetailItem label="Items to be Purchased" value={request.purchaseItems} />
                        </div>
                    </div>
                )}
                
                {request.requestReason === 'Other' && (
                     <div className="pl-4 border-l-2">
                        <DetailItem label="Purpose with Detail" value={request.otherPurpose} />
                    </div>
                )}
            </div>
            
            <Separator />
            
            <div className="grid grid-cols-2 gap-4">
                <DetailItem label="Requisition Type" value={request.requisitionType} />
                <DetailItem label="Request Generated" value={format(new Date(request.requestGeneratedDate), 'PPP p')} />
                <DetailItem label="Status" value={request.status} />
                <DetailItem label="Current Stage" value={getStage()} />
            </div>
            
            {request.pdComments && <Separator />}
            <DetailItem label="PD Comments" value={request.pdComments} />
            
            {(request.driverId || request.vehicleId) && <Separator />}
             <div className="grid grid-cols-2 gap-4">
                <DetailItem label="Driver Name" value={request.driverName} />
                <DetailItem label="Driver Contact" value={request.driverContact} />
                <DetailItem label="Vehicle ID" value={request.vehicleId} />
                <DetailItem label="Vehicle Type" value={request.vehicleType} />
            </div>

            {request.managerComments && <Separator />}
            <DetailItem label="Supervisor Comments" value={request.managerComments} />

            {request.supervisorComments && <Separator />}
            <DetailItem label="Manager Comments" value={request.supervisorComments} />
        </div>
        <DialogFooter>
            <p className="text-xs text-muted-foreground mr-auto">Request ID: {request.id}</p>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
